### ISSUE TITLE
Standup meeting issues

### ISSUE THREAD

**Issue by Ceejayski** [iam-Akshat/react-calc#8]
The app's UI looks good and it's functionality works well mostly, here are some issues to improve on:
- There seems to be a problem with the app, where you try a smaller number like 1 minus a bigger number like 8, it gives an entirely wrong answer without pressing the equals to button.

Good work Akshat the app looks good

**Comment by iam-Akshat** [comment]
The app works correctly, the issue you are describing does not make sense. Thanks
